import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ProviderStore from "@/store/ProviderStore";
import { ContextProvider } from "@/context/ContextApi";
import TanstackProvider from "@/tanstack/TanstackProvider";
import Navbar from "@/components/attendee/Navbar";
import Footer from "@/components/attendee/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <ProviderStore>
          <TanstackProvider>
            <ContextProvider>
              <Navbar />
              {children}
              <Footer />
            </ContextProvider>
          </TanstackProvider>
        </ProviderStore>

        <Toaster />
      </body>
    </html>
  );
}
